stages:
  - build

variables:
  IMAGE_USER: ketab

xcala_play_build:
  image: docker:20.10
  script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $REGISTRY
    - docker build . --build-arg NEXUS_KEY
  retry: 2
  stage: build
